# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713febbdf5cd3593a71e841706be1c7210c7174037d7c423d344a17398d26ced384ec79950ae256ab4beacc00fe4c44ef8f4ac222b909e36439e74a001ece9d2

test:
  secret_key_base: 8cf108bbf5b0312e01113e3776540445d3443e82d29f3dfd351a2ad4cd0b6849ffa7d64647b60f15cc72c4dc2a6b6d93c7d34d9ad469e85e85b22b45bbabce75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
